class MediaDomainError(Exception): ...

class ImageNotFoundError(MediaDomainError): ...

class DuplicateImageError(MediaDomainError): ...

class InvalidFolderError(MediaDomainError): ...

class InvalidMoveError(MediaDomainError): ...

class ImageConflictError(MediaDomainError): ...

class ImageSaveError(MediaDomainError): ...

class ImageOperationError(MediaDomainError): ...

class ImageCreationError(MediaDomainError): ...
