from app.domain.errors import DomainError


class MediaDomainError(DomainError): ...


class ImageNotFoundError(MediaDomainError): ...


class InvalidFolderError(MediaDomainError): ...


class InvalidMoveError(MediaDomainError): ...


class ImageConflictError(MediaDomainError): ...


class ImageSaveError(MediaDomainError): ...


class ImageOperationError(MediaDomainError): ...


class ImageCreationError(MediaDomainError): ...
